version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_URI
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - echo "環境変数をロード"
      - whoami
      - pwd
      - ls -la
      - export ENV_PATH="$(pwd)/.env"
      - echo $ENV_PATH
      - . $ENV_PATH
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - echo "環境変数の値:" ${ORIGINAL_IMAGE_NAME} ${MOUNT_DEST} ${ENTRY_PATH}
      - >
        docker build
        --build-arg ORIGINAL_IMAGE_NAME=${ORIGINAL_IMAGE_NAME}
        --build-arg MOUNT_DEST=${MOUNT_DEST}
        --build-arg ENTRY_PATH=${ENTRY_PATH}
        -t $ECR_URI:$IMAGE_TAG
        -f Dockerfile .
      - docker tag $ECR_URI:$IMAGE_TAG $ECR_URI:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $ECR_URI:$IMAGE_TAG
      - docker push $ECR_URI:latest
